// apps/www/src/routes/register.tsx
import { A } from "@solidjs/router";
import { Title } from "../components/seo/title";
import { Button } from "../components/ui/button";
import { FormControl } from "../components/ui/form-control";
import { Label } from "../components/ui/label";
import { Input } from "../components/ui/input";
import { Show, createSignal } from "solid-js";
import { createRegisterMutation } from "../api/auth/auth.query";

export function Register() {
  const registerMutation = createRegisterMutation();

  const [email, setEmail] = createSignal("");
  const [username, setUsername] = createSignal("");
  const [password, setPassword] = createSignal("");
  const [confirmPassword, setConfirmPassword] = createSignal("");

  const passwordMatches = () => password() === confirmPassword();

  const handleSubmit = (e: SubmitEvent) => {
    e.preventDefault();

    if (!passwordMatches()) {
      return;
    }

    registerMutation.mutate({
      email: email(),
      username: username(),
      password: password(),
    });
  };

  return (
    <>
      <Title>Register</Title>

      <main class="max-w-screen-sm mx-auto py-10">
        <h1 class="font-medium text-2xl mb-8">Register</h1>

        <form onSubmit={handleSubmit} class="flex flex-col gap-4">
          <FormControl>
            <Label>Email</Label>
            <Input type="email" value={email()} onInput={(e) => setEmail(e.target.value)} />
          </FormControl>

          <FormControl>
            <Label>Username</Label>
            <Input type="text" value={username()} onInput={(e) => setUsername(e.target.value)} />
          </FormControl>
          <FormControl>
            <Label>Password</Label>
            <Input
              type="password"
              value={password()}
              onInput={(e) => setPassword(e.target.value)}
            />
          </FormControl>
          <FormControl>
            <Label>Confirm Password</Label>
            <Input
              type="password"
              value={confirmPassword()}
              onInput={(e) => setConfirmPassword(e.target.value)}
            />
          </FormControl>

          <Show when={!passwordMatches()}>
            <p class="text-red-500">Passwords do not match</p>
          </Show>

          <Button type="submit" disabled={!passwordMatches()}>
            Register
          </Button>
        </form>

        <div class="mt-8 grid grid-cols-1 md:grid-cols-2 gap-3">
          <A href="/login" class="text-blue-500 hover:underline">
            Already have an account?
          </A>
        </div>
      </main>
    </>
  );
}

// apps/www/src/routes/register/+page.svelte
<script lang="ts">
	import { goto, invalidateAll } from '$app/navigation';
	import { register } from '$lib/api/auth/auth.fetch';
	import Form from '$lib/components/form/Form.svelte';
	import FormControlLabel from '$lib/components/form/FormControl/FormControlLabel.svelte';
	import FormControlRoot from '$lib/components/form/FormControl/FormControlRoot.svelte';
	import Button from '$lib/components/ui/Button.svelte';
	import Input from '$lib/components/ui/Input.svelte';
	import { createMutation } from '@tanstack/svelte-query';
	import type { FormEventHandler } from 'svelte/elements';

	let username = $state('');
	let email = $state('');
	let password = $state('');
	let passwordRepeat = $state('');

	let isMatchingPasswords = $derived.by(() => password === passwordRepeat);

	const registerMutation = createMutation({
		mutationFn: register
	});

	const handleSubmit: FormEventHandler<HTMLFormElement> = async (e) => {
		e.preventDefault();

		if (!isMatchingPasswords) {
			return;
		}

		await $registerMutation.mutateAsync({
			username,
			email,
			password
		});

		await invalidateAll();
		await goto('/');
	};
</script>

<svelte:head>
	<title>Register</title>
</svelte:head>

<Form onsubmit={handleSubmit}>
	<FormControlRoot>
		<FormControlLabel>Username</FormControlLabel>
		<Input type="text" name="username" bind:value={username} />
	</FormControlRoot>

	<FormControlRoot>
		<FormControlLabel>Email</FormControlLabel>
		<Input type="email" name="email" bind:value={email} />
	</FormControlRoot>

	<FormControlRoot>
		<FormControlLabel>Password</FormControlLabel>
		<Input type="password" name="password" bind:value={password} />
	</FormControlRoot>

	<FormControlRoot>
		<FormControlLabel>Repeat password</FormControlLabel>
		<Input type="password" name="passwordRepeat" bind:value={passwordRepeat} />
	</FormControlRoot>

	{#if !isMatchingPasswords}
		<p class="text-red-500 text-sm">Passwords do not match</p>
	{/if}

	<Button type="submit">Register</Button>
</Form>

<p class="py-4 text-center">
	<a class="text-blue-500 hover:underline" href="/login">Already have an account?</a>
</p>
