// apps/www/src/lib/components/header/Header.svelte
<script>
	import { getAuthContext } from '$lib/context/auth-context.svelte';
	import HeaderItem from './HeaderItem.svelte';
	import LogOutButton from './LogOutButton.svelte';

	let auth = getAuthContext();
	let isLoggedIn = $derived(!!auth.user);
</script>

<header class="bg-indigo-600 p-3 flex items-center justify-between mb-8">
	<a href="/">
		<h1 class="font-bold text-white text-xl">⛩️ Shihai</h1>
	</a>

	<div>
		<menu class="flex items-center">
			{#if isLoggedIn}
				<HeaderItem href="/poll/create">Create poll</HeaderItem>
				<HeaderItem href="/profile">Profile</HeaderItem>
				<LogOutButton />
			{/if}

			{#if !isLoggedIn}
				<HeaderItem href="/login">Login</HeaderItem>
				<HeaderItem href="/register">Register</HeaderItem>
			{/if}
		</menu>
	</div>
</header>

// apps/www/src/components/header.tsx
import { JSX, Show } from "solid-js";
import { A } from "@solidjs/router";
import { createLogoutMutation, getCurrentUser } from "../api/auth/auth.query";

export function Header() {
  const user = getCurrentUser();

  return (
    <header class="p-4 flex justify-between border-b">
      <a href="/">
        <h1 class="font-semibold text-xl">SHIHAI</h1>
      </a>

      <menu class="flex items-center space-x-2">
        <HeaderItem href="/">Home</HeaderItem>
        <HeaderItem href="/poll/new">New Poll</HeaderItem>
        <Show when={!!user()}>
          <HeaderItem href="/profile">{user()!.username}</HeaderItem>
          <LogoutButton />
        </Show>
        <Show when={!user()}>
          <HeaderItem href="/login">Log in</HeaderItem>
          <HeaderItem href="/register">Register</HeaderItem>
        </Show>
      </menu>
    </header>
  );
}

type MenuItemProps = {
  href: string;
  children: JSX.Element;
};

function HeaderItem({ href, children }: MenuItemProps) {
  return (
    <li>
      <A class="text-gray-700 hover:underline hover:text-gray-900" href={href}>
        {children}
      </A>
    </li>
  );
}

function LogoutButton() {
  const logoutMutation = createLogoutMutation();

  const handleLogout = () => {
    logoutMutation.mutate();
  };

  return (
    <li>
      <button class="text-gray-700 hover:underline hover:text-gray-900" onClick={handleLogout}>
        Log out
      </button>
    </li>
  );
}
