// apps/www/src/lib/components/ui/Button.svelte
<script lang="ts">
	import { cn } from '$lib/cn';
	import type { HTMLButtonAttributes } from 'svelte/elements';

	type Props = HTMLButtonAttributes;

	let { class: className, children, ...props }: Props = $props();
</script>

<button
	class={cn(
		'bg-indigo-600 text-white px-2 text-sm hover:bg-indigo-500 transition-all rounded h-8 font-medium',
		className
	)}
	{...props}
>
	{@render children?.()}
</button>

// apps/www/src/components/ui/button.tsx
import { ComponentProps } from "solid-js";
import { cn } from "../../lib/cn";

export type ButtonProps = ComponentProps<"button">;

export function Button({ class: className, ...props }: ButtonProps) {
  return (
    <button
      class={cn(
        "px-4 py-2 bg-green-500 hover:bg-green-600 transition-colors h-10 text-white font-medium rounded",
        className,
      )}
      {...props}
    />
  );
}
